#!/usr/bin/env python3

import sys
import os
import argparse
import subprocess
import numpy as np

# Ensure helper modules or scripts in the same directory can be imported/resolved
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.insert(0, script_dir)

# Physical Constants for Gold (197Au) Reactions
M_AU = 196.966569        # Molar mass [g/mol]
RHO_AU = 19.32           # Density of Gold [g/cm3]
NA = 6.02214076e23       # Avogadro constant [atoms/mol]
A_ISO = 1.0              # Monoisotopic 197Au

# Reaction Product Half-Lives [seconds]
T_HALF_198AU = 232856.6  # 198Au from (n,g)  (~2.6951 days)
T_HALF_196AU = 532790.4  # 196Au from (n,2n) (~6.1665 days)
T_HALF_194AU = 141120.0  # 194Au from (n,4n) (~39.2 hours)

# Standard n_TOF pulse intensity assumed in calculate_sacs3.py spectrum files
PROTONS_PER_STANDARD_PULSE = 7.0e12

# Hard-coded SACS parameters passed downstream to calculate_sacs3.py
TARGET_ISO = "Au197"
SAMPLE_MAT = "Au"
DEFAULT_BIN_MODE = "0"
DEFAULT_EXTRAP_MODE = "1"
DEFAULT_INTERP_FLAG = "1/E"  # Hard-coded to 1/E interpolation

USAGE_TEXT = """
Usage Examples:
  python3 scripts/calculate_counts3.py
  python3 scripts/calculate_counts3.py input_NEAR_BurialDating MCecc 200
  python3 scripts/calculate_counts3.py input_EAR1CC_BurialDating MCecc 500
"""

def resolve_spectrum_file(area, flux_variant="MCecc"):
    """
    Resolves neutron spectrum filename from area string and validates
    that the corresponding file exists in the data/ folder.
    """
    area_clean = str(area).strip()
    
    if area_clean == "NEAR":
        spectrum_file = f"NEAR-{flux_variant}"
    elif area_clean == "EAR1CC":
        spectrum_file = "Z21-EAR1"
    elif area_clean in ["EAR1FC", "EAR1"]:
        spectrum_file = "Z21-EAR1FC"
    elif area_clean == "EAR2":
        spectrum_file = "Z22-EAR2"
    else:
        spectrum_file = f"{area_clean}-{flux_variant}"

    target_path = os.path.join("data", spectrum_file)

    if not os.path.exists(target_path):
        sys.stderr.write(
            f"\n[FATAL ERROR] Spectrum file error for area '{area_clean}' with variant '{flux_variant}':\n"
            f"  Expected file path : '{target_path}'\n"
            f"  Status            : FILE NOT FOUND or INCOMPATIBLE VARIANT\n"
            f"Execution terminated.\n\n"
        )
        sys.exit(1)

    return spectrum_file


def get_fms_filename(mass_g, diam_mm, line_id):
    """
    Constructs the expected F_ms Monte Carlo filename based on the geometry
    and reaction type (ng, n2n, n4n).
    """
    line_str = str(line_id).strip()
    if line_str == '41':
        react = "n4n"
    elif line_str in ['21', '22']:
        react = "n2n"
    else:
        react = "ng"
    
    diam_str = f"{float(diam_mm):.1f}"
    mass_str = f"{float(mass_g):.4f}"
    
    return f"tempfiles/fms_d{diam_str}_m{mass_str}_{react}.dat"


def get_decay_constant(line_id):
    """Returns decay constant lambda [1/s] according to product isotope."""
    line_str = str(line_id).strip()
    if line_str == '41':
        t_half = T_HALF_194AU
    elif line_str in ['21', '22']:
        t_half = T_HALF_196AU
    else:
        t_half = T_HALF_198AU
    return np.log(2.0) / t_half


def calculate_counts_from_cols(cols, flux_variant="MCecc", bpd=200):
    """
    Computes total calculated counts using zero-indexed positional columns
    via calculate_sacs3.py. Automatically detects and applies pointwise 
    Monte Carlo F_ms correction if the corresponding file exists.
    """
    area          = str(cols[0]).strip()
    fthick_mm     = float(cols[1])
    sample_name   = cols[2]
    mass_g        = float(cols[3])
    diam_mm       = float(cols[4])
    thick_mm      = float(cols[5])
    line_id       = str(cols[6]).strip()
    egam_keV      = float(cols[7])
    Igam          = float(cols[8])
    epsi          = float(cols[9])
    c_table       = float(cols[10])
    tirr_s        = float(cols[11])
    twait_s       = float(cols[12])
    tcount_s      = float(cols[13])
    total_protons = float(cols[14])
    bif           = float(cols[15])  # Beam Interception / Correction Factor

    # Dynamic reaction selector based on line ID
    if line_id == '41':
        react = "41"
    elif line_id in ['21', '22']:
        react = "n2n"
    else:
        react = "ng"

    lam = get_decay_constant(line_id)

    # Resolve specific F_ms file generated by workflow and calculate_ms3.py
    fms_file = get_fms_filename(mass_g, diam_mm, line_id)
    fms_found = os.path.exists(fms_file)
    if not fms_found:
        fms_file = "NONE" # calculate_sacs3.py will default to F_ms = 1.0 if not found

    # 1. Target nuclei (NT) from mass
    NT = (mass_g / M_AU) * NA * A_ISO

    # 2. Sample Area [cm2] and Areal density [atoms/barn] from mass & diameter
    diam_cm = diam_mm * 0.1
    area_cm2 = np.pi * (0.5 * diam_cm)**2
    atoms_per_barn = (NT / area_cm2) * 1e-24

    # Derived Thickness Check (in mm)
    thick_calc_cm = mass_g / (RHO_AU * area_cm2)
    thick_calc_mm = thick_calc_cm * 10.0

    if thick_mm > 0.0:
        rel_diff = abs(thick_calc_mm - thick_mm) / thick_mm
        if rel_diff > 0.01:
            sys.stderr.write(
                f"[WARNING] Sample '{sample_name}' (line {line_id}): "
                f"Thickness mismatch > 1% ({rel_diff * 100.0:.2f}%)! "
                f"Derived from mass & diam: {thick_calc_mm:.4f} mm, "
                f"Input table thick_mm: {thick_calc_mm:.4f} mm\n"
            )

    spectrum_file = resolve_spectrum_file(area, flux_variant)

    # Resolve exact path to calculate_sacs3.py relative to this script file
    sacs_script_path = os.path.join(script_dir, "calculate_sacs3.py")

    # 3. Invoke calculate_sacs3.py with pointwise F_ms file
    cmd = [
        sys.executable, sacs_script_path,
        spectrum_file,           # <nspectrum>
        TARGET_ISO,              # <iso> (Au197)
        react,                   # <react>
        str(fthick_mm),          # <fthick_mm>
        SAMPLE_MAT,              # <sample_mat> (Au)
        str(atoms_per_barn),     # <sample_thick_atoms_per_barn>
        str(bpd),                # <bpd>
        DEFAULT_BIN_MODE,        # fine-grid option
        DEFAULT_EXTRAP_MODE,     # neutron flux extrapolation option
        DEFAULT_INTERP_FLAG,     # neutron flux interpolation shape option ("1/E")
        fms_file                 # Pointwise F_ms cross-section file path (or 'NONE')
    ]

    try:
        res = subprocess.run(cmd, capture_output=True, text=True, check=True)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"SACS calculation command failed for sample '{sample_name}' (line {line_id}, react {react}).\n"
            f"Command run: {' '.join(cmd)}\n"
            f"STDOUT:\n{e.stdout}\n"
            f"STDERR:\n{e.stderr}"
        )

    # 4. Parse output summary line
    combined_output = res.stdout + "\n" + res.stderr
    matching_lines = [
        line for line in combined_output.splitlines() 
        if line.lstrip("#").strip().startswith("line:")
    ]

    if not matching_lines:
        raise RuntimeError(
            f"calculate_sacs3.py executed successfully but did not produce summary output.\n"
            f"Command executed: {' '.join(cmd)}\n"
            f"Full Output Received:\n{combined_output}"
        )

    line_out = matching_lines[0]
    tokens = line_out.lstrip("#").strip().split()
    
    try:
        f_nn_pulse       = float(tokens[4])     # f-nn/pp
        sacs_b           = float(tokens[5])     # Unattenuated SACS [b]
        f_sacs_b         = float(tokens[6])     # Filtered SACS [b]
        ssf_sacs_b       = float(tokens[8])     # Self-shielded SACS [b]
        ms_sacs_b        = float(tokens[9])     # Multiple-scattering corrected SACS [b]
    except (IndexError, ValueError) as e:
        raise RuntimeError(f"Failed to parse tokens from: '{line_out}'") from e

    # Effective cross section in cm2 (using the fully corrected ms_sacs_b)
    sigma_cm2 = ms_sacs_b * 1e-24

    # Equivalent standard 7e12 proton pulses
    equivalent_pulses = total_protons / PROTONS_PER_STANDARD_PULSE

    # Total integrated neutron fluence density hitting the sample [neutrons/cm2]
    if "Z21" in spectrum_file or "EAR1" in spectrum_file or "Z22" in spectrum_file or "EAR2" in spectrum_file:
        phi_tot = (f_nn_pulse / area_cm2) * equivalent_pulses * bif
    else:
        phi_tot = f_nn_pulse * equivalent_pulses * bif

    # 5. Activation Calculation using channel-specific decay constant
    R = (NT * phi_tot * sigma_cm2) / tirr_s
    A0 = R * (1.0 - np.exp(-lam * tirr_s))  # Activity at End of Irradiation [Bq]
    
    # Specific Activity at End of Irradiation [Bq/g]
    a0_per_g = A0 / mass_g if mass_g > 0 else 0.0

    # Total calculated gamma counts
    counts_calc = (A0 / lam) * np.exp(-lam * twait_s) * (1.0 - np.exp(-lam * tcount_s)) * epsi * Igam

    display_react = "n4n" if react == "41" else react
    return area, sample_name, line_id, display_react, fthick_mm, mass_g, diam_mm, thick_mm, sacs_b, f_sacs_b, ssf_sacs_b, ms_sacs_b, phi_tot, a0_per_g, counts_calc, c_table, ratio_val(counts_calc, c_table), bif, spectrum_file, fms_found


def ratio_val(c_calc, c_table):
    return c_calc / c_table if c_table > 0 else 0.0


def load_raw_data_lines(filename):
    """Loads data lines ignoring comments (#) or blank lines."""
    if not os.path.exists(filename):
        raise FileNotFoundError(f"Input file '{filename}' not found.")

    data_rows = []
    with open(filename, 'r') as f:
        for line in f:
            line_str = line.strip()
            if not line_str or line_str.startswith("#"):
                continue
            cols = line_str.split()
            if len(cols) >= 16:
                data_rows.append(cols)

    return data_rows


def main():
    parser = argparse.ArgumentParser(
        description="Calculate activation counts using calculate_sacs3.py engine with dynamic Pointwise F_ms correction.",
        epilog=USAGE_TEXT,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("input_file", nargs="?", default="input_NEAR", help="Input table file")
    parser.add_argument(
        "flux_variant", nargs="?", default="MCecc",
        help="NEAR flux variant spectrum option or flux filename tag (default: MCecc)"
    )
    parser.add_argument(
        "bpd", nargs="?", type=int, default=200,
        help="Bins per decade for external binning (default: 200)"
    )

    if len(sys.argv) == 1 and not os.path.exists("input_NEAR"):
        parser.print_help()
        print("\n[Error] Default input file 'input_NEAR' was not found.")
        sys.exit(1)

    args = parser.parse_args()

    if not os.path.exists(args.input_file):
        parser.print_help()
        print(f"\n[Error] Specified input file '{args.input_file}' was not found.")
        sys.exit(1)

    data_rows = load_raw_data_lines(args.input_file)
    areas_present = set(str(cols[0]).strip() for cols in data_rows)

    resolved_spectrums = sorted(list(set(
        resolve_spectrum_file(cols[0], args.flux_variant) for cols in data_rows
    )))
    spec_str = ", ".join(resolved_spectrums)

    # Process all sample rows first to assess F_ms status across the table
    processed_results = []
    missing_fms_count = 0

    for cols in data_rows:
        res_tuple = calculate_counts_from_cols(
            cols, flux_variant=args.flux_variant, bpd=args.bpd
        )
        fms_found = res_tuple[-1]
        if not fms_found:
            missing_fms_count += 1
        processed_results.append(res_tuple)

    # Build Header metadata
    fms_status_msg = "Auto-detect per sample line (tempfiles/fms_*.dat)"
    if missing_fms_count > 0:
        fms_status_msg += f" -- NOTE: File missing for {missing_fms_count} sample(s); F_ms = 1.0 assumed"

    meta_headers = [
        f"# Input Table           : {args.input_file}",
        f"# Resolved Spectrum(s)  : {spec_str}",
        f"# F_ms Correction Mode  : {fms_status_msg}"
    ]

    if "NEAR" in areas_present:
        meta_headers.append(f"# NEAR Variant Option   : {args.flux_variant}")

    meta_headers.extend([
        f"# Neutron Flux Shape    : {DEFAULT_INTERP_FLAG}",
        f"# SACS Engine           : Python (calculate_sacs3.py)",
        f"# SACS Target Isotope   : {TARGET_ISO}",
        f"# SACS Sample Material  : {SAMPLE_MAT}",
        f"# SACS Bins per Decade  : {args.bpd}",
        f"# SACS Binning Mode     : {DEFAULT_BIN_MODE} (Master grid)",
        f"# SACS Extrapolation    : {DEFAULT_EXTRAP_MODE}",
        f"# SACS Interp Flag      : {DEFAULT_INTERP_FLAG}"
    ])

    for line in meta_headers:
        print(line)

    # Tight Header Definition with exactly 1 blank space between heading tags
    header_fmt1 = f"#{'1':<10} {'2':<9} {'3':<4} {'4':<5} {'5':<10} {'6':<8} {'7':<8} {'8':<9} {'9':<10} {'10':<10} {'11':<10} {'12':<10} {'13':<14} {'14':<12} {'15':<11} {'16':<11} {'17':<10} {'18':<6}"
    header_fmt2 = f"#{'area':<9} {'sample':<9} {'line':<4} {'react':<5} {'fthick[mm]':<10} {'mass[g]':<8} {'diam[mm]':<8} {'thick[mm]':<9} {'SACS[b]':<10} {'f-SACS[b]':<10} {'ssf-SACS[b]':<10} {'ms-SACS[b]':<10} {'n_total[n/cm2]':<14} {'A0[Bq/g]':<12} {'Cgam_calc':<11} {'Cgam_exp':<11} {'Ratio(C/E)':<10} {'BIF':<6}"
    divider_line = "#" * len(header_fmt2)

    table_headers = f"{header_fmt1}\n{header_fmt2}\n{divider_line}"
    print(table_headers)

    output_lines = meta_headers + [table_headers]

    for res_tuple in processed_results:
        area, sample_name, line_id, react, fthick_mm, mass_g, diam_mm, thick_mm, sacs_b, f_sacs, ssf_sacs, ms_sacs, phi_tot, a0_per_g, c_calc, c_table, ratio, bif, spec_used, fms_found = res_tuple

        # Data formatting matching exact field widths with single-space separators
        line_str = f"{area:<10} {sample_name:<9} {line_id:<4} {react:<5} {fthick_mm:<10.2f} {mass_g:<8.4f} {diam_mm:<8.1f} {thick_mm:<9.4f} {sacs_b:<10.3f} {f_sacs:<10.3f} {ssf_sacs:<10.3f} {ms_sacs:<10.3f} {phi_tot:<14.3e} {a0_per_g:<12.3e} {c_calc:<11.3e} {c_table:<11.3e} {ratio:<10.3f} {bif:<6.4f}"
        print(line_str)
        output_lines.append(line_str)

    output_filename = "newtable"
    with open(output_filename, "w") as out_file:
        out_file.write("\n".join(output_lines) + "\n")

    print(f"\n# Summary table saved to '{output_filename}'.")


if __name__ == "__main__":
    main()
